name: Deploy to Cloud Run

on:
  push:
    branches:
    - 'main'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: plex-discord-feed
  REGION: us-west1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build
        run: |-
          docker build --build-arg APP_URL=${{ secrets.APP_URL }} --build-arg DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }} --build-arg REDIS_URL=${{ secrets.REDIS_URL }} --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} .

      - name: Publish
        run: |-
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}

      - name: Deploy to Cloud Run
        id: plex-discord-feed
        uses: google-github-actions/deploy-cloudrun@v0.10.1
        with:
          service: ${{ env.SERVICE }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
          region: ${{ env.REGION }}

      - name: Show Output
        run: echo ${{ steps.plex-discord-feed.outputs.url }}
